<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="logo.png" />
    <None Remove="tlo.jpg" />
    <None Remove="zdjecia\DeliriumNcv-Vm5e.ttf" />
    <None Remove="zdjecia\DeliriumNeonNcv-J1AK.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="logo.png" />
    <Resource Include="tlo.jpg" />
    <Resource Include="zdjecia\DeliriumNcv-Vm5e.ttf" />
    <Resource Include="zdjecia\DeliriumNeonNcv-J1AK.ttf" />
  </ItemGroup>

</Project>
