<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="tlo.jpg" />
    <None Remove="zdjecia\invader1.gif" />
    <None Remove="zdjecia\invader2.gif" />
    <None Remove="zdjecia\invader3.gif" />
    <None Remove="zdjecia\invader4.gif" />
    <None Remove="zdjecia\invader5.gif" />
    <None Remove="zdjecia\invader6.gif" />
    <None Remove="zdjecia\invader7.gif" />
    <None Remove="zdjecia\invader8.gif" />
    <None Remove="zdjecia\player.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="tlo.jpg" />
    <Resource Include="zdjecia\invader1.gif" />
    <Resource Include="zdjecia\invader2.gif" />
    <Resource Include="zdjecia\invader3.gif" />
    <Resource Include="zdjecia\invader4.gif" />
    <Resource Include="zdjecia\invader5.gif" />
    <Resource Include="zdjecia\invader6.gif" />
    <Resource Include="zdjecia\invader7.gif" />
    <Resource Include="zdjecia\invader8.gif" />
    <Resource Include="zdjecia\player.png" />
  </ItemGroup>

</Project>
