<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="logo.png" />
    <None Remove="sounds\battleMusic.mp3" />
    <None Remove="sounds\buttonClick.wav" />
    <None Remove="sounds\enemyDeath.wav" />
    <None Remove="sounds\menuMusic.mp3" />
    <None Remove="sounds\spaceshipDeath.wav" />
    <None Remove="sounds\spaceshipShot.wav" />
    <None Remove="tlo.jpg" />
    <None Remove="zdjecia\invader1.gif" />
    <None Remove="zdjecia\invader2.gif" />
    <None Remove="zdjecia\invader3.gif" />
    <None Remove="zdjecia\invader4.gif" />
    <None Remove="zdjecia\invader5.gif" />
    <None Remove="zdjecia\invader6.gif" />
    <None Remove="zdjecia\invader7.gif" />
    <None Remove="zdjecia\invader8.gif" />
    <None Remove="zdjecia\player.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="sounds\battleMusic.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="sounds\buttonClick.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="sounds\enemyDeath.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="sounds\menuMusic.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="sounds\spaceshipDeath.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="sounds\spaceshipShot.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="logo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="tlo.jpg" />
    <Resource Include="zdjecia\invader1.gif" />
    <Resource Include="zdjecia\invader2.gif" />
    <Resource Include="zdjecia\invader3.gif" />
    <Resource Include="zdjecia\invader4.gif" />
    <Resource Include="zdjecia\invader5.gif" />
    <Resource Include="zdjecia\invader6.gif" />
    <Resource Include="zdjecia\invader7.gif" />
    <Resource Include="zdjecia\invader8.gif" />
    <Resource Include="zdjecia\player.png" />
  </ItemGroup>

</Project>
